# EJEMLO 1
# name: "Deploy"

# on:
#   push:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - run: echo "🚨 Inicio de Workflow - Consola"

#       - name: Setup Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.12"
#       - run: python src/main.py

# # EJEMPLO 2
# name: Deploy to server # Nombre

# on: push # Evento

# jobs:
#   first_job:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Hola mundo
#         run: echo "🚨 Hola mundo"

#   second_job:
#     # if: false
#     if: ${{ github.ref == 'refs/heads/main' }}
#     needs: first_job

#     # Se puede con listas
#     # needs:
#     #   - first-job
#     #   - other-job

#     runs-on: ubuntu-latest
#     name: Segundo trabajo

#     steps:
#       - name: Working
#         # shell: bash
#         run: ls -al

#       - name: Action
#         uses: actions/checkout@v4

# # EJEMPLO 3
# name: Deploy to server # Nombre

# on: push # Evento

# jobs:
#   first_job:
#     name: Primer trabajo
#     runs-on: ubuntu-latest
#     outputs:
#       variable: ${{ steps.step_share.outputs.variable }}

#     steps:
#       - name: List environment variables
#         run: echo $GITHUB_OUTPUT

#       - name: Share information
#         id: step_share
#         run: echo "variable=Hola Mundo" >> $GITHUB_OUTPUT

#       - name: Get message
#         run: echo ${{ steps.step_share.outputs.variable }}

#   second_job:
#     name: Segundo trabajo
#     runs-on: ubuntu-latest
#     needs: first_job
#     env:
#       variable: ${{ needs.first_job.outputs.variable }}
#     steps:
#       - name: Ejecuntando segundo trabajo
#         run: echo "🚨 Segundo step"

#       - name: Imprimir variable con interpolación
#         run: echo ${{ env.variable }}

#       - name: Imprimir variable
#         run: echo "$variable"

# EJEMPLO 4
name: Artefactos

on: push

jobs:
  first_job:
    name: Primer trabajo
    runs-on: ubuntu-latest
    outputs:
      variable: ${{ steps.step_share.outputs.variable }}

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  second_job:
    name: Segundo trabajo
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Mostrar contenido
        run: cat test.log
